[package]
name = "coeconverter_rs"
version = "0.1.0"
authors = ["User <jordi@kaucasus.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "0.23.12"
structopt = "0.3.20"
clap = "2.33.3"
